### PR TITLE
correct serialization for label abuse_types

### PR DESCRIPTION
**Pull request by Jonahss**
This fixes an error where I had the wrong serialization for the `$abuse_type` property. It was coming in with quotes, so it looked like:
```
{
  "$abuse_type": "\"payment_abuse\""
}
```

this solves it, are you ok with the approach?

@mathieukempe

### CODE REVIEW

**Comment by mathieukempe** [comment]
Looks good to me, thanks!

**Comment by Jonahss** [comment]
Would you be able to publish to NuGet as well? @mathieukempe

**Comment by mathieukempe** [comment]
Hey @Jonahss 
Sorry it's pushed to nuget now
Should probably spend a bit of time to automate

**Comment by Jonahss** [comment]
Thanks!

Yeah I know what you mean. Depends on the framework. I used to maintain a java project, and it never seemed worth it to set up auto-publishing :/

**Pull request merged**
