### PR TITLE
Added support for synchronous score getting from Event API

### PR DESCRIPTION
**Pull request by SergeyLaptsevich**
See the following link for Sift documentation https://siftscience.com/developers/docs/curl/automation-apis/synchronous-actions). Basically I just added a parameter for all events whether it should return Score or not

### CODE REVIEW

**Comment by mathieukempe** [comment]
Awesome, thanks

**Comment by SergeyLaptsevich** [comment]
@mathieukempe why didn't you merge my changes? I find them useful and someone else might need them in place. Should I implement some adjustments?

**Comment by mathieukempe** [comment]
hey Sergey,

The changes were merge

**Comment by mathieukempe** [comment]
Woops sorry, the changes weren't merged. I have fixed that now. 
Thanks for letting me know

**Pull request merged**
