### PR TITLE
Updates!

### PR DESCRIPTION
**Pull request by Jonahss**
Includes all the changes by @bountye and then my updates:

add more PaymentType enums
add $payment_methods to Account

### CODE REVIEW

**Comment by Jonahss** [comment]
fixes #13  and #16

**Comment by Jonahss** [comment]
@mathieukempe Do you have time to merge this and publish a new version of the NuGet package?

**Comment by mathieukempe** [comment]
sorry for the delay, it's now merged and pushed to nuget

**Comment by Jonahss** [comment]
Thanks! I'll send pull requests for bug fixes if I broke anything >.<

**Pull request merged**
